Бариев 2.1.8
clonediff/dotnet-homeworks-2 pull request #12
Opened 2022-10-27 14:55 UTC by clonediff

2022-10-28 15:20 UTC, flayexz requested changes

2022-10-28 15:20 UTC, flayexz commented on Homework8/Hw8/Calculator/Parser.cs
> +            result = double.NaN;
как-то не очень, может все-таки бул?

2022-10-28 15:20 UTC, flayexz commented on Homework8/Hw8/Controllers/CalculatorController.cs
> +            return Messages.DivisionByZeroMessage;
как-то многовато логики для контроллера, может вынести это куда-то?

2022-10-28 15:20 UTC, flayexz commented on Homework8/Hw8/Program.cs
> +        builder.Services.AddScoped<ICalculator, Calculator.Calculator>();
а почему scoped?

2022-10-28 15:50 UTC, clonediff commented on Homework8/Hw8/Program.cs
> +        builder.Services.AddScoped<ICalculator, Calculator.Calculator>();
Думаешь singleton лучше будет в этом случае?

2022-10-28 15:58 UTC, flayexz commented on Homework8/Hw8/Program.cs
> +        builder.Services.AddScoped<ICalculator, Calculator.Calculator>();
ну в данном случае смысла от scoped нет, поэтому зачем нам создавать каждый раз объекты, если можно сделать это 1 раз

2022-10-28 16:01 UTC, flayexz commented on Homework8/Hw8/Controllers/CalculatorController.cs
> +            return Messages.DivisionByZeroMessage;
кстати, сейчас заметил, у тебя возвращается просто строка, давай обернем ее в BadRequest

2022-10-28 16:05 UTC, flayexz commented
еще один момент, почему бы не сделать интерфейс для парсера и добавить его через di

2022-10-28 16:12 UTC, flayexz requested changes

2022-10-28 16:12 UTC, flayexz commented on Homework8/Hw8/Controllers/CalculatorController.cs
> +    private double Calculate(ICalculator calculator, double arg1, Operation operation, double arg2)
давай перенесем этот метод в Calculator, не думаю что такой метод должен быть в контроллере

2022-10-30 13:47 UTC, flayexz requested changes

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Calculator/CalculatorService.cs
> +        private ICalculator _calculator;
давай их ридонли сделаем

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Calculator/CalculatorService.cs
> +        public CalculatorService([FromServices]ICalculator calculator,
тут [FromServices] уже убрать можно

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Calculator/IParser.cs
> +        Result<(double val1, Operation oper, double val2), string> TryParseAllArguments(string arg1, string operation, string arg2);
чет сложно, может тут применим TryParse подход с out параметром, и еще разобьем на 2 метода: парс аргумента и парс операции

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Calculator/Parser.cs
> +    private bool TryParseArgument(string value, out double result)
вот, я бы эти методы публичными сделал просто, а от TryParseAllArguments отказался бы

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Calculator/Result.cs
> +    public class Result<T, TError>
а давай просто Result<T>, при этом ErrorValue поменяем на ErrorText с типом string,  так мы упростим код

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Controllers/CalculatorController.cs
> +        return BadRequest(result.ErrorValue);
отлично, так это и должно выглядеть

2022-10-30 13:47 UTC, flayexz commented on Homework8/Hw8/Calculator/CalculatorService.cs
> +        public Result<string, string> GetCalculationResult(string val1,
не очень понял идею с приватным и публичным методом, почему не сделать 1 публичный?

2022-10-30 15:53 UTC, flayexz requested changes

2022-10-30 15:53 UTC, flayexz commented on Homework8/Hw8/Interfaces/ICalculatorService.cs
> +        Result<string> GetCalculationResult(string arg1, string operation, string aeg2);
очепятка, arg2

2022-10-30 15:53 UTC, flayexz commented on Homework8/Hw8/Services/CalculatorService.cs
> +        public Result<string> GetCalculationResult(string arg1,
в начале не заметил, почему не double?

2022-10-30 15:53 UTC, flayexz commented on Homework8/Hw8/Services/CalculatorService.cs
> +                return Result<string>.Error(Messages.DivisionByZeroMessage);
вот эти проверки можно в приватный метод вынести

2022-10-30 16:35 UTC, flayexz approved these changes

2022-10-30 16:35 UTC, merged