Бариев 2.1.11
clonediff/dotnet-homeworks-2 pull request #15
Opened 2022-11-22 07:27 UTC by clonediff

2022-11-22 12:44 UTC, flayexz requested changes

2022-11-22 12:44 UTC, flayexz commented on Homework11/Hw11/Services/MathCalculator/Calculator.cs
> +        private class CalculatorExpressionVisitor
почему это приватный класс внутри калькулятора?

2022-11-22 12:44 UTC, flayexz commented on Homework11/Hw11/Services/MathCalculator/Calculator.cs
> +        private class CalculatorExpressionVisitor
Так, я видимо в прошлой дз проглядел. Короче есть класс EpressionVisitor, можно от него наследоваться и переопределить нужные методы

2022-11-22 15:44 UTC, clonediff commented on Homework11/Hw11/Services/MathCalculator/Calculator.cs
> +        private class CalculatorExpressionVisitor
В тз сказано, что наследоваться нельзя)

2022-11-23 10:36 UTC, flayexz approved these changes

2022-11-23 10:36 UTC, merged